### ISSUE TITLE
同步的yml会在同步后被覆盖

### ISSUE THREAD

**Issue by Castle1984** [insChow/auto_repo-sync#3]
有个问题想请教大佬
发现每次一旦同步完成后，整个项目是搬移过来了，但是sync-scripts.yml这个文件同步后就会被目标仓库覆盖掉，下次就没办法自动同步了
有什么办法能解决啊？

**Comment by insChow** [comment]
不用担心，所同步的仓库下次会自动同步，你要是想保留这个同步yml文件，单独给它一个分支即可。

**Comment by Castle1984** [comment]
哦哦哦，懂了懂了，感谢大佬
